### ISSUE TITLE
(BUG) Occasional illegal battery level warnings

### ISSUE THREAD

**Issue by ckowalski-1** [tonesto7/homebridge-hubitat-tonesto7#143]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 73
-  Hubitat App Version: 2.5.14
-  Homebridge Plugin Version: 2.5.14
-  Homebridge Version: 1.4.0 
-  NodeJS Version: 12.14.1

## Expected Behavior
No out of range warnings

## Current Behavior
Seeing occasional warnings in the logs:
[homebridge-hubitat-tonesto7] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 113 exceeded maximum of 100. See https://git.io/JtMGR for more info.

## Steps to Reproduce (for bugs)
Seen on homebrige startup and then occasionally while running

## Context
No impact, other than noticed this in the logs.  Haven't checked all devices to ensure battery level is correct so can't say for sure this is totally benign 

---
When running with debug enabled I get:

`[3/15/2022, 12:45:23 PM] [homebridge-hubitat-tonesto7] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number 113 exceeded maximum of 100. See https://git.io/JtMGR for more info.`
`[3/15/2022, 12:45:23 PM] [homebridge-hubitat-tonesto7] Error: 
    at BatteryLevel.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at BatteryLevel.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2049:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at BatteryLevel.<anonymous> (/usr/lib/node_modules/homebridge-hubitat-tonesto7/src/HE_DeviceCharacteristics.js:34:21)
    at BatteryLevel.emit (events.js:223:5)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at BatteryLevel.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at BatteryLevel.Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at BatteryLevel.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2207:22)`

**Comment by ckowalski-1** [comment]
Not seeing this anymore.  Don't know if it was the Pi reboot, or the Hubitat update ...
