### ISSUE TITLE
(BUG) Adaptive Lighting not working on 2.10 beta 7

### ISSUE THREAD

**Issue by kfraleigh** [tonesto7/homebridge-hubitat-tonesto7#233]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?:23
-  Hubitat App Version: 2.10.0
-  Homebridge Plugin Version: 2.10 -7
-  Homebridge Version: 1.8.5
-  NodeJS Version:20.12.2

## Expected Behavior
Color temperature should change with Adaptive Lighting enabled 

## Current Behavior
Color temperature doesn’t change after updating to beta 7 from 2.9.4

## Steps to Reproduce (for bugs)
Updated HE app to 2.10
Updated HB app to 2.10
Adaptive lighting shows enabled in Apple Home
CT doesn’t change for lights
Reverting to HB app version 2.9.4 resolves issue. 

Let me know if you need error logs or if I am missing something. 

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by ppkhoa** [comment]
+1 to this issue, I'm seeing these in the logs complaining about unknown property for Adaptive Lighting:

```
[12/3/2024, 5:37:44 PM] [Hubitat-v2] initializeAccessory (fromCache: false) | Name: Bedroom | Error: TypeError: Cannot read properties of undefined (reading 'AdaptiveLightingControllerMode')
TypeError: Cannot read properties of undefined (reading 'AdaptiveLightingControllerMode')
    at PlatformAccessory.addAdaptiveLightingController (/homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Accessories.js:440:38)
    at DeviceCharacteristics.light (/homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_DeviceCharacteristics.js:410:24)
    at /homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Accessories.js:131:48
    at Array.forEach (<anonymous>)
    at HE_Accessories.configureCharacteristics (/homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Accessories.js:127:22)
    at HE_Accessories.initializeAccessory (/homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Accessories.js:90:25)
    at HE_Platform.updateDevice (/homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Platform.js:308:46)
    at /homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Platform.js:268:63
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-hubitat-tonesto7/src/HE_Platform.js:268:38
```
Current workaround is to downgrade back to plugin v2.9.4

**Comment by kfraleigh** [comment]
I decided to try 2.10 beta 7 again, also updating to the 3.0 app in Hubitat and HB 2.0 latest beta, and HE isn't communicating with the HB app (404 error). I had copy/pasted the new config for the app into HB. I also tried generating a new key and pasting that in to the config, but same error. Downgraded the HE app to the latest release and it communicated, but no adaptive lighting. Downgraded HB and HB plugin to latest release and everything works again.
