### ISSUE TITLE
Update 1.5.4 causes Homebridge to quit

### ISSUE THREAD

**Issue by walksonair** [tonesto7/homebridge-hubitat-tonesto7#3]
Just updated Hubitat plugin to 1.5.4 and tried unlocking...HomeKit started saying the lock was not responding. Then, as I was checking my terminal, homebridge looked like it quit. here is the output:

```
/usr/local/lib/node_modules/homebridge-hubitat-tonesto7/accessories/he_st_accessories.js:261
                        platform.clientApi.runCommand(callback, device.deviceid, 'unlock');
                                           ^

TypeError: Cannot read property 'runCommand' of undefined
    at Characteristic.LockTargetState.<anonymous> (/usr/local/lib/node_modules/homebridge-hubitat-tonesto7/accessories/he_st_accessories.js:261:44)
    at Characteristic.LockTargetState.emit (events.js:182:13)
    at Characteristic.LockTargetState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at HAPServer.emit (events.js:182:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

Reran w/ DEBUG=* homebridge -D and the following preceded the same error as above:

```
Accessory [Homebridge] Getting value for Characteristic "Lock Target State" +1ms
  Accessory [Homebridge] Got Characteristic "Lock Target State" value: 1 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Lock Current State" +0ms
  Accessory [Homebridge] Got Characteristic "Lock Current State" value: 1 +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +40s
  HAPServer [34:12:6D:13:BE:29] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 0 +0ms
/usr/local/lib/node_modules/homebridge-hubitat-tonesto7/accessories/he_st_accessories.js:261
                        platform.clientApi.runCommand(callback, device.deviceid, 'unlock');
                                           ^

TypeError: Cannot read property 'runCommand' of undefined
    at Characteristic.LockTargetState.<anonymous> (/usr/local/lib/node_modules/homebridge-hubitat-tonesto7/accessories/he_st_accessories.js:261:44)
    at Characteristic.LockTargetState.emit (events.js:182:13)
    at Characteristic.LockTargetState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at HAPServer.emit (events.js:182:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by tonesto7** [comment]
I will look into this as soon as I get into the office

**Comment by tonesto7** [comment]
Update to v1.5.5 and you should be good... sorry for the mistake

**Comment by walksonair** [comment]
No probemo, thanks for getting to it so quickly!
