### ISSUE TITLE
Update 1.5.5 causes Homebridge to not start.

### ISSUE THREAD

**Issue by csteele-PD** [tonesto7/homebridge-hubitat-tonesto7#4]
sudo npm i -g homebridge-hubitat-tonesto7
+ homebridge-hubitat-tonesto7@1.5.5
updated 1 package in 2.362s

Results in:

$ homebridge     
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by csteele-PD** [comment]
1.1.5 is a coincidence. The Mac I was running it on had been upgraded to Mojave a week before and the first time to fully restart homebridge (during an upgrade) exposed the flaw.

The solution was to uninstall everything including Node.js and NPM, Upgrade X-code (to allow the compile of node-gyp) and reinstall it all.
